// Seed data: 8 sample medical products across 4 categories

import { Product, Category } from '@/types';

export const seedCategories: Omit<Category, 'id'>[] = [
  {
    name: 'Endoscopes',
    slug: 'endoscopes',
    icon: 'Telescope',
    description: 'High-definition flexible and rigid endoscopy systems for minimally invasive diagnostics and surgery.',
    productCount: 2,
    createdAt: new Date().toISOString(),
  },
  {
    name: 'Diagnostic Machines',
    slug: 'diagnostic-machines',
    icon: 'ScanLine',
    description: 'Advanced diagnostic imaging and screening equipment for accurate clinical assessments.',
    productCount: 2,
    createdAt: new Date().toISOString(),
  },
  {
    name: 'Surgical Equipment',
    slug: 'surgical-equipment',
    icon: 'Scissors',
    description: 'Precision surgical instruments and operating room equipment for safe, efficient procedures.',
    productCount: 2,
    createdAt: new Date().toISOString(),
  },
  {
    name: 'Monitoring Devices',
    slug: 'monitoring-devices',
    icon: 'HeartPulse',
    description: 'Real-time patient monitoring systems for ICU, OT, and bedside care.',
    productCount: 2,
    createdAt: new Date().toISOString(),
  },
];

export const seedProducts: Omit<Product, 'id'>[] = [
  // ── Endoscopes ──
  {
    name: 'HD Flexible Video Endoscope System V-100',
    slug: 'hd-flexible-video-endoscope',
    category: 'Endoscopes',
    categoryId: '',
    shortDescription: 'Full HD flexible video endoscope with 140° wide-angle view, LED cold illumination, and IPX7 waterproof design.',
    fullDescription: `The HD Flexible Video Endoscope by TH Raamed is engineered for superior gastrointestinal diagnostics. Featuring a high-resolution CMOS sensor with full 1080p HD output, this endoscope delivers crystal-clear imaging for accurate diagnosis.\n\nThe 140° wide-angle field of view ensures comprehensive visualization of the examination area, while the advanced LED cold-light illumination provides consistent, shadow-free lighting. The flexible insertion tube (Ø9.8mm) is designed for patient comfort, and the fully waterproof construction (IPX7) allows complete immersion for thorough sterilization.\n\nIdeal for gastroscopy, colonoscopy, and bronchoscopy procedures in hospitals and outpatient clinics.`,
    specifications: [
      { key: 'Image Sensor', value: 'CMOS 1/6" Full HD (1080p)' },
      { key: 'Field of View', value: '140° Wide Angle' },
      { key: 'Working Length', value: '1100mm' },
      { key: 'Insertion Tube Diameter', value: '9.8mm' },
      { key: 'Illumination', value: 'LED Cold Light' },
      { key: 'Bending Range', value: 'Up 210° / Down 120°' },
      { key: 'Waterproof Rating', value: 'IPX7 Certified' },
    ],
    price: 'Price on Request',
    images: ['/images/hero_doctor_team.png'],
    status: 'active',
    featured: true,
    quoteClicks: 34,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Rigid Arthroscope Precision Optic 30°',
    slug: 'rigid-arthroscope-system',
    category: 'Endoscopes',
    categoryId: '',
    shortDescription: 'Precision rigid arthroscope with 30° optic, autoclavable stainless steel body, and HD camera head.',
    fullDescription: `The Rigid Arthroscope System is a complete solution for minimally invasive orthopedic surgery. The 4mm diameter, 30° angled optic provides optimal visualization of joint spaces, while the autoclavable stainless steel construction ensures reliable sterilization.\n\nPaired with a high-resolution HD camera head (1920×1080), the system delivers sharp, true-color images to any compatible monitor. The integrated fiber-optic light guide connects to standard light sources for bright, uniform illumination.\n\nSuitable for knee, shoulder, hip, and ankle arthroscopy. Complete system includes arthroscope, camera head, light cable, and protective case.`,
    specifications: [
      { key: 'Optic Angle', value: '30°' },
      { key: 'Diameter', value: '4.0mm' },
      { key: 'Working Length', value: '175mm' },
      { key: 'Camera Resolution', value: '1920 × 1080 Full HD' },
      { key: 'Material', value: 'Medical-Grade Stainless Steel' },
      { key: 'Sterilization', value: 'Autoclavable (134°C)' },
    ],
    price: 'Price on Request',
    images: ['/images/hero_doctor_team.png'],
    status: 'active',
    featured: false,
    quoteClicks: 18,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ── Diagnostic Machines ──
  {
    name: 'Digital X-Ray System DR-500 Pro',
    slug: 'digital-xray-system-dr500',
    category: 'Diagnostic Machines',
    categoryId: '',
    shortDescription: 'High-speed flat-panel digital radiography system with AI-assisted image processing and DICOM connectivity.',
    fullDescription: `The DR-500 Digital X-Ray System represents the latest in flat-panel radiography technology. Featuring a large 17" × 17" amorphous silicon detector, it captures high-resolution images with exceptional detail at a significantly lower radiation dose than conventional systems.\n\nThe AI-assisted image processing engine automatically optimizes contrast, brightness, and edge enhancement, reducing retake rates and improving diagnostic confidence. Full DICOM 3.0 connectivity ensures seamless integration with existing PACS and HIS/RIS infrastructure.\n\nThe motorized table and wall-stand configurations support a wide range of examinations, from chest and abdomen to extremity and spine imaging. Ideal for hospitals, diagnostic centers, and urgent care facilities.`,
    specifications: [
      { key: 'Detector Type', value: 'Flat Panel, Amorphous Silicon' },
      { key: 'Detector Size', value: '17" × 17" (43cm × 43cm)' },
      { key: 'Resolution', value: '3.6 lp/mm (148μm pixel)' },
      { key: 'Generator Power', value: '50kW High Frequency' },
      { key: 'Image Preview', value: '< 3 seconds' },
      { key: 'Connectivity', value: 'DICOM 3.0, HL7' },
    ],
    price: 'Price on Request',
    images: ['/images/hero_doctor_team.png'],
    status: 'active',
    featured: true,
    quoteClicks: 52,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Portable Ultrasound Scanner ProScan U60',
    slug: 'portable-ultrasound-scanner-proscan-u60',
    category: 'Diagnostic Machines',
    categoryId: '',
    shortDescription: 'Compact, lightweight portable ultrasound with 15" HD touchscreen, multi-probe support, and Color Doppler.',
    fullDescription: `The ProScan U60 is a premium portable ultrasound system that combines clinical-grade imaging with exceptional portability. Weighing just 5.5kg, it is perfect for point-of-care, bedside, and field diagnostics.\n\nThe 15" high-resolution LED touchscreen display provides vivid B-mode, M-mode, and Color Doppler imaging. Support for convex, linear, and micro-convex probes makes the U60 versatile across OB/GYN, abdominal, cardiac, vascular, and musculoskeletal applications.\n\nAdvanced features include tissue harmonic imaging, speckle reduction, auto-optimization, and a built-in battery lasting up to 2 hours of continuous scanning. Export images and cine loops via USB or DICOM.`,
    specifications: [
      { key: 'Display', value: '15" LED Touch Screen' },
      { key: 'Imaging Modes', value: 'B, M, Color Doppler, PW, CW' },
      { key: 'Probe Support', value: 'Convex, Linear, Micro-Convex' },
      { key: 'Weight', value: '5.5 kg' },
      { key: 'Battery Life', value: '2 Hours Continuous' },
    ],
    price: 'Price on Request',
    images: ['/images/hero_doctor_team.png'],
    status: 'active',
    featured: true,
    quoteClicks: 47,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ── Surgical Equipment ──
  {
    name: 'Electrosurgical Unit ESU-400 Generator',
    slug: 'electrosurgical-unit-esu400',
    category: 'Surgical Equipment',
    categoryId: '',
    shortDescription: 'Microprocessor-controlled 400W electrosurgical generator with bipolar & monopolar modes and auto-impedance sensing.',
    fullDescription: `The ESU-400 Electrosurgical Unit is a high-performance, microprocessor-controlled generator designed for cutting, coagulation, and blended surgical modes. With 400 watts of monopolar power and 120 watts of bipolar power, it handles everything from delicate tissue dissection to heavy coagulation.\n\nAdvanced Automatic Impedance Sensing (AIS) technology continuously monitors tissue impedance and auto-adjusts output for consistent surgical effect, reducing thermal damage and improving patient outcomes.`,
    specifications: [
      { key: 'Monopolar Power', value: '400W max' },
      { key: 'Bipolar Power', value: '120W max' },
      { key: 'Modes', value: 'Cut, Coag, Blend, Bipolar' },
      { key: 'Frequency', value: '470 kHz' },
      { key: 'Safety', value: 'REM, Leakage Protection' },
    ],
    price: 'Price on Request',
    images: ['/images/hero_doctor_team.png'],
    status: 'active',
    featured: false,
    quoteClicks: 21,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Surgical LED Operating Light SL-700 Dual Dome',
    slug: 'surgical-led-operating-light-sl700',
    category: 'Surgical Equipment',
    categoryId: '',
    shortDescription: 'Ceiling-mounted dual-dome surgical LED light with 160,000 lux intensity and color temperature control.',
    fullDescription: `The SL-700 Surgical LED Operating Light delivers exceptional shadow-free illumination for operating rooms. The dual-dome configuration with 128 high-CRI LEDs per dome provides up to 160,000 lux of bright, natural-color light.\n\nAdjustable color temperature (3,700K–5,000K) allows surgeons to optimize visualization for different tissue types and procedures.`,
    specifications: [
      { key: 'Light Intensity', value: '160,000 Lux (center)' },
      { key: 'Color Temp', value: '3,700K – 5,000K adjustable' },
      { key: 'CRI Index', value: 'Ra ≥ 97' },
      { key: 'LED Lifespan', value: '50,000+ hours' },
    ],
    price: 'Price on Request',
    images: ['/images/hero_doctor_team.png'],
    status: 'active',
    featured: false,
    quoteClicks: 16,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ── Monitoring Devices ──
  {
    name: 'Multi-Parameter Patient Monitor PM-8000 ICU',
    slug: 'multi-parameter-patient-monitor-pm8000',
    category: 'Monitoring Devices',
    categoryId: '',
    shortDescription: '12.1" bedside patient monitor with ECG, SpO2, NIBP, temperature, respiration, and IBP/CO2 support.',
    fullDescription: `The PM-8000 Multi-Parameter Patient Monitor is a comprehensive bedside monitoring solution for ICU, OT, and emergency care. The 12.1" high-resolution TFT color display shows up to 8 waveforms simultaneously for real-time multi-parameter tracking.\n\nStandard parameters include 3/5-lead ECG, SpO2, NIBP, temperature, and respiration. Network-ready with HL7 interface.`,
    specifications: [
      { key: 'Display', value: '12.1" Color TFT (8 Waveforms)' },
      { key: 'ECG', value: '3/5 Lead Standard' },
      { key: 'SpO2', value: 'Masimo / Nellcor Compatible' },
      { key: 'Data Storage', value: '96 Hours Trend' },
    ],
    price: 'Price on Request',
    images: ['/images/hero_doctor_team.png'],
    status: 'active',
    featured: true,
    quoteClicks: 41,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    name: 'Fingertip Pulse Oximeter OxiSense Pro',
    slug: 'fingertip-pulse-oximeter-oxisense-pro',
    category: 'Monitoring Devices',
    categoryId: '',
    shortDescription: 'Medical-grade fingertip pulse oximeter with OLED display, perfusion index, and alarm function.',
    fullDescription: `The OxiSense Pro Fingertip Pulse Oximeter is a compact yet powerful SpO2 monitoring device designed for clinical and point-of-care use. Dual-color OLED display shows SpO2, pulse rate, perfusion index (PI), and pulse bar graph.`,
    specifications: [
      { key: 'SpO2 Range', value: '70% – 100% (±2%)' },
      { key: 'Pulse Rate', value: '30 – 250 bpm (±2 bpm)' },
      { key: 'Display', value: 'Dual-Color OLED' },
      { key: 'Certifications', value: 'CE, FDA 510(k)' },
    ],
    price: 'Price on Request',
    images: ['/images/hero_doctor_team.png'],
    status: 'active',
    featured: false,
    quoteClicks: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
